### ISSUE TITLE
Page contents pasted to artwork URL when failed

### ISSUE THREAD

**Issue by ghost** [realoksi/foobar2000-catbox#10]
This issue was submitted on the behalf of another user.

Catbox went down very recently, and it seems that this uploader tries to parse the site code instead of waiting or handling it in any better way. What appears to have happened on my friend's end is that when Error 502 is passed by the API, instead of some kind of handling, instead the uploader will paste the contents of the HTML to the Artwork URL instead.
Example: `"KMFDM|Blitz": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>",`

The end result is that the presence bugs out and does something like this, where the large image key is completely invisible and the small image key seemingly takes the stage. The weird display is probably a Discord limitation, however it's a result of this strange input in the Artwork URL json.
![image](https://github.com/user-attachments/assets/681b8869-25fe-46f8-ab08-41bf4189c7c4)

Theoretically this could be fixed by removing the offending line from `art_urls.json` but I would expect the uploader to handle this issue a little better. I don't know if this is an issue with foo_discord_rich or the uploader itself, but I decided to send the issue here first. There appears to be no helpful console output when this happens, likely due to the fact it was successfully parsed to the json.

The outage is not the issue here, it's that the uploader seems to parse the actual page instead of doing nothing, or a less desirable but possible solution: just entering null as the URL like how foo_discord_rich seems to. Again, I don't know how plausible this is, but trying to parse the webpage isn't it.

**Comment by ghost** [comment]
This behavior might be related to foo_discord_rich issue #69 but I'm unsure.

**Comment by realoksi** [comment]
You're right, it looks like after performing the request I wasn't even checking the response code.. oops.
Normally when artwork is successfully uploaded, the response page body should be nothing but the resulting URL to the artwork. Since the program isn't checking the response code, it's treating the 502 error body the same as a successful plain-text URL even though it's now actually an HTML page. As a result, the entire error page is simply being written to `stdout`.

It seems that catbox came back online just as I was looking into this, so at least it'll be working correctly again. Regardless, I'll be pushing a fix for this soon. Hopefully next time they have an outage this will then be handled properly.

As for issue #69 of foo_discord_rich, at least *this* issue (#10) doesn't appear to be related. I'll be sure to look into it more though.

**Comment by ghost** [comment]
Yup, good to know this was an oversight and not an error on my friend and I's end. Thank you for the response!
I figured the issue would be related but guess not. I wish you luck on working on the issue, if there's anything else I can do, I should be free.

Perhaps for further testing the handling, you could possibly spoof an HTML response (perhaps 403 for testing) through HOSTS in some way. The code may not be open, but since the outage basically affected Catbox site-wide, maybe the original API PHP file isn't even needed, and you can just 403 the entire site? Just an idea.

Edit: Misread your last message.

**Comment by ghost** [comment]
Leaving a final update on this and I will be leaving this thread. The new update to fix this issue seems to have resolved some issues involving larger artwork on my end when I was testing for my foo_discord_rich issue, so I thank you for that.

**Comment by ghost** [comment]
Did a final test since Catbox is once again down. Program now works as intended, console prints this:
```
Error:
SubprocessExecutor error: process timed out
```

The only issue is that now the artwork is nulled similar to foo_discord_rich issue #69, which is both interesting and may be more helpful for that issue in particular. This issue is outside of foobar2000-catbox's reach most likely, so the issue can stay closed.
