### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ucm211** [realoksi/foobar2000-catbox#14]
please implement [litter.catbox.moe](https://litterbox.catbox.moe/tools.php), make it optional to disable jpeg encoding, ability to get cover art from archives (.7z│.zip│.rar│.tar) and, thumbnail generator for videos to provide cover art support

**Comment by realoksi** [comment]
I'm going to close this since Litterbox is now the default upload service and you can completely disable encoding through the new config.
I may look into the other two suggestions also - they'll need some investigating as I'm unsure how foo_discord_rich handles things like archives and especially videos
