### ISSUE TITLE
artwork uploader exited with status: 259 and error: Process timed out

### ISSUE THREAD

**Issue by afgks** [realoksi/foobar2000-catbox#6]
The uploader seems to have trouble with this cover:

![cover](https://github.com/realoksi/foobar2000-catbox/assets/11691936/af2f56a8-23e3-41c0-b9d8-476fda4ed882)

To be fair, this isn't an error unique to this uploader. The first python script [here](https://gist.github.com/mechabubba/db1200c05fbbecf753b23c92ee8e9271) also gives the same error, but the experimental script doesn't work and the author doesn't seem to be active.

**Comment by realoksi** [comment]
Can confirm I get the same error code when using this image.

I've created and tested a bunch of samples with varying sizes, also tested the cover you provided. By default the timeout for uploading with the foo_discord_rich plugin is 10 seconds but can be changed in the configuration menu. It seemed as I got past 5MB sized samples it was failing more often. Increasing the timeout to 15 seconds helped. My upload speed just isn't the greatest.

My uploader doesn't resize or compress the image, it just sends it straight to catbox. I didn't implement any downscaling or compression logic originally because I personally didn't have any covers that exceeded even 3MB, so this wasn't an issue for me.

I've pushed a quick implementation tagged as [v1.0.2-alpha](https://github.com/realoksi/foobar2000-catbox/releases/tag/v1.0.2-alpha) that will always resize the image to 512x512 regardless of its height/width or file size (even if it's already smaller than 512). I believe *for now* this size is appropriate for the preview in Discord. Please try it out and let me know if you encounter any issues with it

**Comment by afgks** [comment]
Hello, the new alpha build fixed the issue, but I wonder if it is possible to not resize the image if it's already small enough to be uploaded to Catbox? I don't like the idea of album art being resized if it's already smaller than 512x512.

**Comment by realoksi** [comment]
> Hello, the new alpha build fixed the issue, but I wonder if it is possible to not resize the image if it's already small enough to be uploaded to Catbox? I don't like the idea of album art being resized if it's already smaller than 512x512.

That alpha build was just something quick I whipped up to "fix" it. The newest production release v1.0.4 *does not* resize the image if it's smaller than 512x512, but will compress it as a jpg. By default it will downscale the image to 500x500, however with this build you can modify that resolution through a config.txt file to whatever you prefer

**Comment by afgks** [comment]
Apologies, I didn't realise you have uploaded a new build! The 1.0.4 release has fixed my issues, thanks.
